import os
from dotenv import load_dotenv

load_dotenv()

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
DB_PATH = os.environ.get("DB_PATH", "state.db")
OPENROUTER_MODEL = os.environ.get("OPENROUTER_MODEL", "")
MAX_CODER_ATTEMPTS = 3
SPRINT_SIZE = 2
RESTART_FLAG = "restart.flag"
MAIN_SCRIPT = "main.py"
CHECK_INTERVAL = 2 
TOOLS_SCHEMA = [
    {
        "name": "web_search",
        "description": "Web search via DuckDuckGo. Useful for finding documentation on Python libraries.",
        "parameters": {"query": "str - the search query"},
    },
    {
        "name": "fetch_url",
        "description": "Fetches the text content of a URL.",
        "parameters": {"url": "str - the URL to fetch"},
    },
    {
        "name": "exec_code",
        "description": "Executes Python code in an isolated sandbox (bwrap). Returns stdout/stderr.",
        "parameters": {
            "code": "str - the Python code to execute",
            "requirements": "list[str] - pip packages to install (optional)",
        },
    },
    {
        "name": "read_file",
        "description": "Reads a file in the output/ folder of the codebase.",
        "parameters": {"path": "str - relative path in output/"},
    },
    {
        "name": "write_file",
        "description": "Writes/creates a file in the output/ folder of the codebase.",
        "parameters": {
            "path": "str - relative path",
            "content": "str - file content",
        },
    },
    {
        "name": "list_files",
        "description": "Lists all files in output/.",
        "parameters": {},
    },
]
STDLIB_IMPORTS = [
    "pytest",
    "unittest",
    "unittest.mock",
    "patch",
    "typing",
    "dataclasses",
    "enum",
    "abc",
    "os",
    "sys",
    "re",
    "json",
    "time",
    "copy",
    "math",
    "pathlib",
    "shutil",
    "tempfile",
    "glob",
    "io",
    "datetime",
    "calendar",
    "collections",
    "itertools",
    "functools",
    "heapq",
    "bisect",
    "threading",
    "multiprocessing",
    "asyncio",
    "concurrent.futures",
    "urllib.request",
    "urllib.parse",
    "http.client",
    "http.server",
    "socket",
    "ssl",
    "logging",
    "traceback",
    "warnings",
    "inspect",
    "pprint",
    "pickle",
    "csv",
    "configparser",
    "xml.etree.ElementTree",
    "html.parser",
    "uuid",
    "hashlib",
    "hmac",
    "secrets",
    "base64",
    "contextlib",
    "weakref",
    "gc",
    "signal",
    "struct",
    "string",
    "textwrap",
    "difflib",
    "fnmatch",
    "argparse",
    "getopt",
    "optparse",
    "cmd",
    "subprocess",
    "platform",
    "stat",
    "pwd",
    "grp",
    "random",
    "statistics",
    "decimal",
    "fractions",
    "zipfile",
    "tarfile",
    "gzip",
    "bz2",
    "zlib",
    "lzma",
    "operator",
    "types",
    "numbers",
    "queue",
    "email",
    "smtplib",
    "mimetypes",
    "codecs",
]